services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - TZ=UTC
      - RABBITMQ_DEFAULT_USER=eduflex
      - RABBITMQ_DEFAULT_PASS=eduflexRabbit1
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    networks:
      - ADSL
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  ADSL:
    external: true

volumes:
  rabbitmq_data:
    driver: local
